### ISSUE TITLE
toggle button and menu overlapping 

### ISSUE THREAD

**Issue by Siddesh0002T** [Siddesh0002T/react-portfolio-2024#2]
when site open in small size devices nav menu hide all links its ok but when we click on menu button it shows link but when link tab open back ground and menu overlap together .

**Comment by mBasak03** [comment]
can you assign me the issue? or should I start by myself?

**Comment by Siddesh0002T** [comment]
Hi @mBasak03 ,

Thank you for reaching out. I'll be happy to assign this issue to you. Please go ahead and start working on it. If you have any questions or need clarification on anything related to the issue, feel free to ask.

Looking forward to your contributions.

Best regards,
@Siddesh0002T

**Comment by Siddesh0002T** [comment]
Thank you @mBasak03

**Comment by mBasak03** [comment]
> Thank you @mBasak03 

Welcome 😊, This is my first PR

**Comment by Siddesh0002T** [comment]
can you fix this @mBasak03 [https://github.com/RubbySoft/fixmate/issues/1](Project URL) for that project 😊
